# Generated by Django 3.0 on 2022-12-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_feature_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
